name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    
    - name: Dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration release
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        artifacts: Jellyfin.Plugin.JellyTweaks
        path: Jellyfin.Plugin.JellyTweaks/bin/*/*/Jellyfin.Plugin.JellyTweaks.dll
