name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Variables
      id: variables
      run: echo ::set-output name=version::$(git describe --tags --always)
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration release
    
    - name: Move
      run: mv Jellyfin.Plugin.JellyTweaks/bin/*/*/Jellyfin.Plugin.JellyTweaks.dll .
    
    - name: Compress
      env:
        version: ${{ steps.variables.outputs.version }}
      run: zip Jellyfin.Plugin.JellyTweaks.zip *.dll
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        artifacts: 'JellyTweaks'
        path: Jellyfin.Plugin.JellyTweaks/bin/*/*/Jellyfin.Plugin.JellyTweaks.zip
